j280 add font style to all the text components
eugeneprib/JabbReactNative pull request #14
Opened 2021-08-27 09:23 UTC by EugeniusGR

![image](https://user-images.githubusercontent.com/35200697/131104952-4e80ed6e-4921-4dc1-9b6a-c8c327c9c134.png)
![image](https://user-images.githubusercontent.com/35200697/131104988-403b8822-c4cb-464b-9da9-6595431f8016.png)
+ Sign In

2021-08-27 09:33 UTC, eugeneprib requested changes

2021-08-27 09:33 UTC, eugeneprib commented on src/components/Heading/styles.ts
> +    fontFamily: 'Raleway-Bold'
We have exported fonts in styles folder

2021-08-27 09:33 UTC, eugeneprib commented on src/screens/Podcast/Podcast.tsx
> +import { View, Image, ImageBackground, TouchableOpacity } from 'react-native'
Imports order please

2021-08-27 10:02 UTC, eugeneprib requested changes

2021-08-27 10:02 UTC, eugeneprib commented on src/components/PlainText/styles.ts
> +    fontFamily: 'Raleway-Medium'
Add global font variable here as well

2021-08-27 13:14 UTC, Denidzio commented on src/screens/Home/Home.tsx
> +            label={`Find this week's hottest podcasts`}
I don't know if we really need such form of text inputting {``}. Because within all project we were using `' '`.

2021-08-27 13:24 UTC, Denidzio requested changes

2021-08-27 13:24 UTC, Denidzio commented on src/components/PlainText/styles.ts
> +
```suggestion
type Styles = {
    text: TextStyle
}
```

2021-08-27 13:24 UTC, Denidzio commented on src/components/PlainText/styles.ts
> +const styles = StyleSheet.create({
```suggestion
const styles = StyleSheet.create<Styles>({
```

2021-08-27 13:24 UTC, Denidzio commented on src/screens/Home/Home.tsx
>            source="https://ca.slack-edge.com/T025CKYU9R7-U0261G9DKRN-0714d7d9b1ae-512"
For example here we are using `" "` and it's confusing

2021-08-27 13:24 UTC, Denidzio commented on src/screens/Home/components/PopularSingleCard/styles.ts
> +    fontSize: 12
Why did you change it?

2021-08-27 13:24 UTC, Denidzio commented on src/screens/Podcast/components/episodeItem.tsx
> +          type={HeadingType.MEDIUM}
```suggestion
          type={HeadingType.SMALL}
```

2021-08-27 13:24 UTC, Denidzio commented on src/screens/Podcast/components/episodeItem.tsx
> +          style={styles.episodeInfoTitle}
```suggestion
```

2021-08-27 13:24 UTC, Denidzio commented on src/screens/Podcast/components/episodeItem.tsx
> +        />
I don't recommend you style the Heading component. Because we have HeadingType for this purpose. If you look on RecentlyPlayedCard heading size you will notice that this is similar to this heading. I have used there `HeadingType.SMALL` and it will be better if you use it too.

2021-08-27 13:24 UTC, Denidzio commented on src/screens/Podcast/components/styles.ts
>    episodeInfoTitle: {
```suggestion
```

2021-08-27 16:48 UTC, EugeniusGR commented on src/screens/Podcast/components/episodeItem.tsx
> +        />
I tried it, its not fit

2021-08-27 16:49 UTC, EugeniusGR commented on src/screens/Home/components/PopularSingleCard/styles.ts
> +    fontSize: 12
the text with this font became very small
I change it so it become more readable

2021-08-27 17:05 UTC, EugeniusGR commented on src/screens/Home/Home.tsx
> +            label={`Find this week's hottest podcasts`}
its for -> '
week ' s

2021-08-27 19:43 UTC, Denidzio requested changes

2021-08-27 19:43 UTC, Denidzio commented on src/components/PlainText/styles.ts
> +const styles: Styles = StyleSheet.create({
```suggestion
const styles = StyleSheet.create<Styles>({
```

2021-08-28 05:35 UTC, Denidzio approved these changes

2021-08-28 07:29 UTC, merged