Task vv/339  add popular singles episodes logic
eugeneprib/JabbReactNative pull request #32
Opened 2021-09-04 19:43 UTC by vitalik-prog

2021-09-05 07:43 UTC, Denidzio requested changes

2021-09-05 07:43 UTC, Denidzio commented on src/screens/Home/Home.tsx
> +  const navigation = useNavigation<PodcastScreenNavigationProp>()
```suggestion
  const navigation = useNavigation<HomeScreenNavigationProp>()
```

2021-09-05 07:43 UTC, Denidzio commented on src/screens/Home/Home.tsx
> +import { PodcastScreenNavigationProp } from '../Podcast/common/types'
```suggestion
import { HomeScreenNavigationProp } from './common/types'
```

2021-09-05 07:43 UTC, Denidzio commented on src/screens/Home/components/PopularSingleCard/PopularSingleCard.tsx
> +  const isCardRight = Boolean(position % EVEN_RATIO !== 0)
Let's avoid this calculation and do it by styles. I think `flexWrap` should help you.

2021-09-06 07:52 UTC, eugeneprib requested changes

2021-09-06 07:52 UTC, eugeneprib commented on src/store/home/index.ts
> +      state.popular = action.payload.slice(
I would change this property name from `popular` to `popularEpisodes`

2021-09-06 08:07 UTC, merged