Task yc/j386 make background white again
eugeneprib/JabbReactNative pull request #38
Opened 2021-09-07 13:51 UTC by EugeniusGR

![image](https://user-images.githubusercontent.com/35200697/132356397-7857b278-848e-4fe3-8daa-f4f3bd8487f9.png)
![image](https://user-images.githubusercontent.com/35200697/132356437-dca19dab-c7c9-4209-8812-ec4d4efce142.png)

2021-09-07 14:02 UTC, Denidzio requested changes
It will be better if we make `background-color` once for each screen through react-navigation.

2021-09-07 14:12 UTC, EugeniusGR commented
> It will be better if we make `background-color` once for each screen through react-navigation.

thats possible when you are using StackNavigation (as we do, and if you look at the code, you will see those lines `cardStyle: { backgroundColor: '#fff' },` , but thats impossible to do with our case, when the tab navigation is inside stack navigation

2021-09-07 14:56 UTC, Denidzio commented
> > It will be better if we make `background-color` once for each screen through react-navigation.
> 
> thats possible when you are using StackNavigation (as we do, and if you look at the code, you will see those lines `cardStyle: { backgroundColor: '#fff' },` , but thats impossible to do with our case, when the tab navigation is inside stack navigation. Tab navigation has this property but we must create container, what is impossible to do with our case

:(

2021-09-07 15:19 UTC, EugeniusGR commented
new button design
![image](https://user-images.githubusercontent.com/35200697/132369967-d19e9548-63f8-4398-9b2b-cccf7b34b0bc.png)

2021-09-08 08:20 UTC, eugeneprib commented on src/screens/Home/styles.ts
> +    backgroundColor: '#fff'
You could just move this as a global styles variable

2021-09-08 08:25 UTC, eugeneprib requested changes
Make tabs background also white

2021-09-09 08:15 UTC, merged