Task dl/j244 add home screen
eugeneprib/JabbReactNative pull request #8
Opened 2021-08-25 15:57 UTC by Denidzio

![image](https://user-images.githubusercontent.com/60543500/130824223-b524094a-6014-45cd-8074-adc7d20ad6b1.png)
![image](https://user-images.githubusercontent.com/60543500/130824256-d491c3c8-328d-4654-8863-cdfae1140ebc.png)

2021-08-25 19:11 UTC, vitalik-prog commented on src/screens/home/components/popularSingleCard/styles.ts
> +}
Is this really necessary hard-typing styles? Maybe it redundant?

2021-08-26 06:18 UTC, Denidzio commented on src/screens/home/components/popularSingleCard/styles.ts
> +}
> Is this really necessary hard-typing styles? Maybe it redundant?

It's convenient to track which styles are compatible with particular component

2021-08-26 07:27 UTC, eugeneprib requested changes

2021-08-26 07:27 UTC, eugeneprib commented on src/screens/home/components/recentlyPlayedCard/RecentlyPlayedCard.tsx
> +import React from 'react'
The folder of the component also needs to be capitalized

2021-08-26 07:27 UTC, eugeneprib commented on src/screens/home/components/userAvatar/styles.ts
> +export { styles }
Usually styles are exported with default export

2021-08-26 07:48 UTC, eugeneprib requested changes

2021-08-26 07:48 UTC, eugeneprib commented on src/screens/home/components/recentlyPlayedCard/RecentlyPlayedCard.tsx
> +import React from 'react'
Screen containers included too

2021-08-26 09:07 UTC, closed without merging